package com.freightflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.data.domain.PageRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import java.time.LocalDate;
import java.util.*;

@Service class AiAssistanceService {
 private final AiModelClient model;private final ObjectMapper mapper;private final EnquiryRepo enquiries;private final QuoteRepo quotes;private final LineRepo lines;private final CustomerRepo customers;private final ContactRepo contacts;private final JdbcTemplate jdbc;
 AiAssistanceService(AiModelClient model,ObjectMapper mapper,EnquiryRepo enquiries,QuoteRepo quotes,LineRepo lines,CustomerRepo customers,ContactRepo contacts,JdbcTemplate jdbc){this.model=model;this.mapper=mapper;this.enquiries=enquiries;this.quotes=quotes;this.lines=lines;this.customers=customers;this.contacts=contacts;this.jdbc=jdbc;}
 UUID tenant(){return SecurityConfig.current().getTenantId();}UUID user(){return SecurityConfig.current().getId();}
 Enquiry enquiry(UUID id){return enquiries.findByIdAndTenantId(id,tenant()).orElseThrow(()->new ApiException(404,"NOT_FOUND","Enquiry not found"));}
 Quotation quote(UUID id){return quotes.findByIdAndTenantId(id,tenant()).orElseThrow(()->new ApiException(404,"NOT_FOUND","Quotation not found"));}
 Customer customer(UUID id){return customers.findByIdAndTenantId(id,tenant()).orElseThrow(()->new ApiException(404,"NOT_FOUND","Customer not found"));}
 void audit(String action,String entity,UUID id,String status){jdbc.update("insert into ai_interaction_log (id,tenant_id,user_id,action_type,related_entity_type,related_entity_id,status) values (?,?,?,?,?,?,?)",UUID.randomUUID(),tenant(),user(),action,entity,id,status);}
 <T> T tracked(String action,String entity,UUID id,java.util.function.Supplier<T> call){try{T result=call.get();audit(action,entity,id,"SUCCESS");return result;}catch(RuntimeException e){audit(action,entity,id,"FAILED");throw e;}}
 static List<String> missing(Enquiry e){List<String> m=new ArrayList<>();if(AiShipmentService.blank(e.getOrigin()))m.add("Origin");if(AiShipmentService.blank(e.getDestination()))m.add("Destination");if(AiShipmentService.blank(e.getCommodity()))m.add("Commodity");if("OCEAN".equals(e.getMode())&&"FCL".equals(e.getCargoType())){if(AiShipmentService.blank(e.getContainerType()))m.add("Container type");if(e.getContainerQuantity()==null)m.add("Container quantity");}if("AIR".equals(e.getMode())&&e.getGrossWeight()==null)m.add("Gross weight");return m;}
 static Map<String,Object> textSchema(){return Map.of("type","object","properties",Map.of("text",Map.of("type","string")),"required",List.of("text"));}
 String text(JsonNode result){String out=result.path("text").asText("").trim();if(out.isEmpty()||out.length()>10000)throw new ApiException(502,"AI_INVALID_RESPONSE","AI returned an invalid response. You can continue manually.");return out;}
 Object draftClarification(UUID id){Enquiry e=enquiry(id);Customer c=customer(e.getCustomerId());List<String> missing=missing(e);if(missing.isEmpty())return Map.of("missingFields",missing,"draft","No essential shipment details are missing.");return tracked("CLARIFICATION_DRAFT","ENQUIRY",id,()->{
  String input="Customer: "+c.getCompanyName()+". Shipment: "+e.getMode()+" "+e.getOrigin()+" to "+e.getDestination()+". Missing: "+String.join(", ",missing)+".";
  String instruction="Write a concise, professional customer message asking only for the listed missing shipment details. Do not claim to send it. Do not invent a contact name, signature, rates, legal requirements, or extra questions. Return JSON text.";
  return Map.of("missingFields",missing,"draft",text(model.generate(instruction,input,textSchema())));
 });}
 Map<String,Object> quoteContext(UUID id){Quotation q=quote(id);Enquiry e=enquiry(q.getEnquiryId());Map<String,Object> c=new LinkedHashMap<>();c.put("quotationNumber",q.getQuotationNumber());c.put("customer",customer(q.getCustomerId()).getCompanyName());c.put("mode",e.getMode());c.put("origin",e.getOrigin());c.put("destination",e.getDestination());c.put("commodity",e.getCommodity());c.put("enquiryContainerType",e.getContainerType());c.put("enquiryContainerQuantity",e.getContainerQuantity());c.put("readyDate",e.getReadyDate());c.put("currency",q.getCurrency());c.put("totalAmount",q.getTotalAmount());c.put("validUntil",q.getValidUntil());c.put("transitTime",q.getTransitTimeText());c.put("terms",q.getTermsAndConditions());c.put("lines",lines.findByTenantIdAndQuotationIdOrderBySortOrder(tenant(),id).stream().map(l->Map.of("description",l.getDescription(),"quantity",l.getQuantity(),"unitPrice",l.getUnitPrice())).toList());return c;}
 Object quoteText(UUID id,String action){Map<String,Object> context=quoteContext(id);String instruction=switch(action){case "text"->"Draft concise professional quotation wording based only on these facts. No new rates, promises, carriers, or guarantees. Return JSON text.";case "email"->"Draft a professional customer-facing quotation email body based only on these facts. Do not say it was sent. No invented terms or rates. Return JSON text.";case "terms"->"Draft standard commercial terms for employee review based only on these facts. Avoid legal guarantees or compliance claims. Clearly state that this is an AI-generated draft. Return JSON text.";default->throw new ApiException(400,"VALIDATION_ERROR","Unknown AI action");};String type=switch(action){case "text"->"QUOTE_TEXT";case "email"->"QUOTE_EMAIL";default->"QUOTE_TERMS";};return tracked(type,"QUOTATION",id,()->Map.of("draft",text(model.generate(instruction,json(context),textSchema())),"label","AI-generated draft — review before sending"));}
 Object quoteCheck(UUID id){Map<String,Object> context=quoteContext(id);List<String> deterministic=new ArrayList<>();if(context.get("currency")==null||String.valueOf(context.get("currency")).isBlank())deterministic.add("Currency is missing");if(context.get("validUntil")==null)deterministic.add("Validity date is missing");if(context.get("readyDate") instanceof LocalDate ready&&context.get("validUntil") instanceof LocalDate valid&&ready.isAfter(valid))deterministic.add("Cargo ready date is later than quotation validity");
  Map<String,Object> schema=Map.of("type","object","properties",Map.of("suggestions",Map.of("type","array","items",Map.of("type","string"))),"required",List.of("suggestions"));
  return tracked("QUOTE_CHECK","QUOTATION",id,()->{JsonNode result=model.generate("Check this quotation for factual inconsistencies against its enquiry. Report suggestions only. Do not change values, rates, or claim certainty. Return JSON suggestions array.",json(context),schema);if(!result.path("suggestions").isArray())throw new ApiException(502,"AI_INVALID_RESPONSE","AI returned an invalid response. You can continue manually.");List<String> suggestions=new ArrayList<>(deterministic);result.path("suggestions").forEach(n->{if(n.isTextual())suggestions.add(n.asText());});return Map.of("suggestions",suggestions);});
 }
 Object customerSummary(UUID id){Customer c=customer(id);List<Enquiry> recent=enquiries.findTop5ByTenantIdAndCustomerIdOrderByCreatedAtDesc(tenant(),id);List<Quotation> recentQuotes=quotes.findTop5ByTenantIdAndCustomerIdOrderByCreatedAtDesc(tenant(),id);Map<String,Object> facts=new LinkedHashMap<>();facts.put("customer",c.getCompanyName());facts.put("recentEnquiries",recent.stream().map(e->Map.of("mode",e.getMode(),"origin",e.getOrigin(),"destination",e.getDestination(),"commodity",e.getCommodity(),"createdAt",e.getCreatedAt())).toList());facts.put("recentQuotations",recentQuotes.stream().map(q->Map.of("status",q.getStatus(),"createdAt",q.getCreatedAt())).toList());return tracked("CUSTOMER_SUMMARY","CUSTOMER",id,()->Map.of("summary",text(model.generate("Summarize only the supplied customer facts. Avoid predictions, speculation, or claims about data outside these recent records. Return JSON text.",json(facts),textSchema()))));}
 Object naturalSearch(String question){Map<String,Object> schema=Map.of("type","object","properties",Map.of("entity",Map.of("type","string","enum",List.of("ENQUIRY","QUOTATION","CUSTOMER")),"mode",AiShipmentService.nullable("string"),"origin",AiShipmentService.nullable("string"),"destination",AiShipmentService.nullable("string"),"customerName",AiShipmentService.nullable("string")),"required",List.of("entity","mode","origin","destination","customerName"));return tracked("NATURAL_LANGUAGE_SEARCH",null,null,()->{
  JsonNode filters=model.generate("Convert the user's search request into the allowed typed filters. Do not generate SQL. For origin/destination use a short literal place name that appears in the request. Unknown filters must be null.",question,schema);String entity=filters.path("entity").asText("");String mode=filters.path("mode").asText("");String origin=filters.path("origin").asText("");String destination=filters.path("destination").asText("");String customerName=filters.path("customerName").asText("");if(!List.of("ENQUIRY","QUOTATION","CUSTOMER").contains(entity)||!mode.isBlank()&&!List.of("OCEAN","AIR","ROAD").contains(mode))throw new ApiException(502,"AI_INVALID_RESPONSE","AI returned an invalid search. Try regular search.");
  UUID customerId=null;if(!customerName.isBlank()){List<Customer> matches=customers.searchTop(tenant(),customerName,PageRequest.of(0,10));customerId=matches.stream().filter(c->c.getCompanyName().equalsIgnoreCase(customerName)).map(Customer::getId).findFirst().orElse(null);if(customerId==null)return Map.of("entity",entity,"results",List.of());}
  Object results=switch(entity){case "ENQUIRY"->enquiries.search(tenant(),!origin.isBlank()?origin:destination,customerId,mode,"",null,PageRequest.of(0,20)).getContent().stream().filter(e->origin.isBlank()||e.getOrigin().toLowerCase().contains(origin.toLowerCase())).filter(e->destination.isBlank()||e.getDestination().toLowerCase().contains(destination.toLowerCase())).map(e->Map.of("id",e.getId(),"label",e.getEnquiryCode(),"detail",e.getOrigin()+" → "+e.getDestination())).toList();case "QUOTATION"->quotes.search(tenant(),"",customerId,"",null,PageRequest.of(0,20)).getContent().stream().map(q->Map.of("id",q.getId(),"label",q.getQuotationNumber(),"detail",q.getStatus())).toList();default->customers.search(tenant(),customerName,"","","",PageRequest.of(0,20)).getContent().stream().map(c->Map.of("id",c.getId(),"label",c.getCompanyName(),"detail",c.getCustomerCode())).toList();};return Map.of("entity",entity,"results",results);
 });}
 String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new ApiException(502,"AI_INVALID_RESPONSE","AI could not prepare this request.");}}
}
