package com.freightflow;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;
import org.springframework.data.domain.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.http.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
import java.math.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api") class BusinessController {
 final JdbcTemplate jdbc;final CustomerRepo customers;final ContactRepo contacts;final AddressRepo addresses;final EnquiryRepo enquiries;final QuoteRepo quotes;final LineRepo lines;
 BusinessController(JdbcTemplate j,CustomerRepo c,ContactRepo ct,AddressRepo a,EnquiryRepo e,QuoteRepo q,LineRepo l){jdbc=j;customers=c;contacts=ct;addresses=a;enquiries=e;quotes=q;lines=l;}
 UUID tenant(){return SecurityConfig.current().getTenantId();} UUID user(){return SecurityConfig.current().getId();}
 Customer customer(UUID id){return customers.findByIdAndTenantId(id,tenant()).orElseThrow(()->new ApiException(404,"NOT_FOUND","Customer not found"));}
 Enquiry enquiry(UUID id){return enquiries.findByIdAndTenantId(id,tenant()).orElseThrow(()->new ApiException(404,"NOT_FOUND","Enquiry not found"));}
 Quotation quote(UUID id){return quotes.findByIdAndTenantId(id,tenant()).orElseThrow(()->new ApiException(404,"NOT_FOUND","Quotation not found"));}
 record ContactInput(@NotBlank String name,@Email @NotBlank String email,@NotBlank String phone,String designation){}
 record AddressInput(@NotBlank String addressType,@NotBlank String line1,String line2,@NotBlank String city,String state,String postalCode,@NotBlank String country){}
 record CustomerInput(@NotBlank String companyName,@NotBlank String customerType,@NotBlank String country,String gstin,String iec,String status,@Valid @NotNull ContactInput primaryContact,List<@Valid AddressInput> addresses){}
 @PostMapping("/customers") @Transactional ResponseEntity<?> createCustomer(@Valid @RequestBody CustomerInput r){Customer c=new Customer();c.setTenantId(tenant());c.setCustomerCode("CUS-"+String.format("%06d",jdbc.queryForObject("select nextval('customer_code_seq')",Long.class)));apply(c,r);customers.save(c);saveContact(c,r.primaryContact());saveAddresses(c,r.addresses());return ResponseEntity.status(201).body(customerDetail(c));}
 @GetMapping("/customers") Object customers(@RequestParam(defaultValue="") String search,@RequestParam(defaultValue="") String type,@RequestParam(defaultValue="") String country,@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return customers.search(tenant(),search,type,country,status,PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::customerSummary);}
 @GetMapping("/customers/{id}") Object getCustomer(@PathVariable UUID id){return customerDetail(customer(id));}
 @PutMapping("/customers/{id}") @Transactional Object updateCustomer(@PathVariable UUID id,@Valid @RequestBody CustomerInput r){Customer c=customer(id);apply(c,r);customers.save(c);CustomerContact ct=contacts.findFirstByTenantIdAndCustomerIdAndPrimaryTrue(tenant(),id).orElseGet(()->{CustomerContact x=new CustomerContact();x.setTenantId(tenant());x.setCustomerId(id);x.setPrimary(true);return x;});ct.setName(r.primaryContact().name());ct.setEmail(r.primaryContact().email());ct.setPhone(r.primaryContact().phone());ct.setDesignation(r.primaryContact().designation());contacts.save(ct);return customerDetail(c);}
 void apply(Customer c,CustomerInput r){if(!List.of("EXPORTER","IMPORTER","FREIGHT_PARTNER","OTHER").contains(r.customerType()))throw new ApiException(400,"VALIDATION_ERROR","Invalid customer type");c.setCompanyName(r.companyName().trim());c.setCustomerType(r.customerType());c.setCountry(r.country());c.setGstin(r.gstin());c.setIec(r.iec());if(r.status()!=null&&!List.of("ACTIVE","INACTIVE").contains(r.status()))throw new ApiException(400,"VALIDATION_ERROR","Invalid customer status");c.setStatus(r.status()==null?"ACTIVE":r.status());}
 void saveContact(Customer c,ContactInput r){CustomerContact x=new CustomerContact();x.setTenantId(tenant());x.setCustomerId(c.getId());x.setPrimary(true);x.setName(r.name());x.setEmail(r.email());x.setPhone(r.phone());x.setDesignation(r.designation());contacts.save(x);}
 void saveAddresses(Customer c,List<AddressInput> xs){if(xs==null)return;for(AddressInput r:xs){CustomerAddress a=new CustomerAddress();a.setTenantId(tenant());a.setCustomerId(c.getId());a.setAddressType(r.addressType());a.setLine1(r.line1());a.setLine2(r.line2());a.setCity(r.city());a.setState(r.state());a.setPostalCode(r.postalCode());a.setCountry(r.country());addresses.save(a);}}
 Map<String,Object> customerSummary(Customer c){Map<String,Object> m=new LinkedHashMap<>();m.put("id",c.getId());m.put("customerCode",c.getCustomerCode());m.put("companyName",c.getCompanyName());m.put("customerType",c.getCustomerType());m.put("country",c.getCountry());m.put("status",c.getStatus());m.put("createdAt",c.getCreatedAt());m.put("primaryContact",contacts.findFirstByTenantIdAndCustomerIdAndPrimaryTrue(tenant(),c.getId()).orElse(null));return m;}
 Object customerDetail(Customer c){Map<String,Object> m=new LinkedHashMap<>(customerSummary(c));m.put("gstin",c.getGstin());m.put("iec",c.getIec());m.put("contacts",contacts.findByTenantIdAndCustomerIdOrderByPrimaryDesc(tenant(),c.getId()));m.put("addresses",addresses.findByTenantIdAndCustomerId(tenant(),c.getId()));m.put("recentEnquiries",enquiries.findTop5ByTenantIdAndCustomerIdOrderByCreatedAtDesc(tenant(),c.getId()));m.put("recentQuotations",quotes.findTop5ByTenantIdAndCustomerIdOrderByCreatedAtDesc(tenant(),c.getId()));return m;}
 record EnquiryInput(@NotNull UUID customerId,UUID contactId,@Email String contactEmail,@NotBlank String mode,@NotBlank String origin,@NotBlank String destination,String portOfLoading,String portOfDischarge,String airportOfOrigin,String airportOfDestination,@NotBlank String commodity,@DecimalMin("0") BigDecimal grossWeight,String weightUnit,@DecimalMin("0") BigDecimal volume,String volumeUnit,@Min(0) Integer packageCount,LocalDate readyDate,String incoterm,String cargoType,String containerType,@Min(0) Integer containerQuantity,boolean pickupRequired,boolean exportCustomsRequired,boolean insuranceRequired,boolean destinationDeliveryRequired,String notes,String status){}
 @PostMapping("/enquiries") @Transactional ResponseEntity<?> createEnquiry(@Valid @RequestBody EnquiryInput r){Enquiry e=new Enquiry();e.setTenantId(tenant());e.setCreatedBy(user());e.setEnquiryCode("ENQ-"+Year.now().getValue()+"-"+String.format("%06d",jdbc.queryForObject("select nextval('enquiry_code_seq')",Long.class)));apply(e,r);enquiries.save(e);return ResponseEntity.status(201).body(enquiryDetail(e));}
 @GetMapping("/enquiries") Object enquiries(@RequestParam(defaultValue="") String search,@RequestParam(required=false) UUID customerId,@RequestParam(defaultValue="") String mode,@RequestParam(defaultValue="") String status,@RequestParam(required=false) LocalDate from,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return enquiries.search(tenant(),search,customerId,mode,status,from==null?null:from.atStartOfDay(ZoneOffset.UTC).toInstant(),PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::enquirySummary);}
 @GetMapping("/enquiries/{id}") Object getEnquiry(@PathVariable UUID id){return enquiryDetail(enquiry(id));}
 @PutMapping("/enquiries/{id}") @Transactional Object updateEnquiry(@PathVariable UUID id,@Valid @RequestBody EnquiryInput r){Enquiry e=enquiry(id);apply(e,r);enquiries.save(e);return enquiryDetail(e);}
 void apply(Enquiry e,EnquiryInput r){customer(r.customerId());if(!List.of("OCEAN","AIR","ROAD").contains(r.mode()))throw new ApiException(400,"VALIDATION_ERROR","Invalid mode");if(r.contactId()!=null&&contacts.findByTenantIdAndCustomerIdOrderByPrimaryDesc(tenant(),r.customerId()).stream().noneMatch(c->c.getId().equals(r.contactId())))throw new ApiException(400,"VALIDATION_ERROR","Contact does not belong to customer");e.setCustomerId(r.customerId());e.setContactId(r.contactId());e.setContactEmail(r.contactEmail()==null||r.contactEmail().isBlank()?null:r.contactEmail().trim());e.setMode(r.mode());e.setOrigin(r.origin());e.setDestination(r.destination());e.setPortOfLoading(r.portOfLoading());e.setPortOfDischarge(r.portOfDischarge());e.setAirportOfOrigin(r.airportOfOrigin());e.setAirportOfDestination(r.airportOfDestination());e.setCommodity(r.commodity());e.setGrossWeight(r.grossWeight());e.setWeightUnit(r.weightUnit());e.setVolume(r.volume());e.setVolumeUnit(r.volumeUnit());e.setPackageCount(r.packageCount());e.setReadyDate(r.readyDate());e.setIncoterm(r.incoterm());e.setCargoType(r.cargoType());e.setContainerType(r.containerType());e.setContainerQuantity(r.containerQuantity());e.setPickupRequired(r.pickupRequired());e.setExportCustomsRequired(r.exportCustomsRequired());e.setInsuranceRequired(r.insuranceRequired());e.setDestinationDeliveryRequired(r.destinationDeliveryRequired());e.setNotes(r.notes());if(r.status()!=null){if(!List.of("NEW","PRICING_PENDING","QUOTED","CANCELLED").contains(r.status()))throw new ApiException(400,"VALIDATION_ERROR","Invalid enquiry status");e.setStatus(r.status());}}
 Map<String,Object> enquirySummary(Enquiry e){Map<String,Object> m=new LinkedHashMap<>();m.put("id",e.getId());m.put("enquiryCode",e.getEnquiryCode());m.put("customerId",e.getCustomerId());m.put("customerName",customer(e.getCustomerId()).getCompanyName());m.put("mode",e.getMode());m.put("origin",e.getOrigin());m.put("destination",e.getDestination());m.put("commodity",e.getCommodity());m.put("status",e.getStatus());m.put("createdAt",e.getCreatedAt());return m;}
 Object enquiryDetail(Enquiry e){Map<String,Object> m=new LinkedHashMap<>(enquirySummary(e));m.put("enquiry",e);m.put("customer",customerSummary(customer(e.getCustomerId())));return m;}
 record LineInput(@NotBlank String description,@NotNull @DecimalMin("0.01") BigDecimal quantity,@NotNull @DecimalMin("0.00") BigDecimal unitPrice){}
 record QuoteInput(@NotBlank String currency,String transitTimeText,@NotNull @FutureOrPresent LocalDate validUntil,@NotBlank String termsAndConditions,String notes,List<@Valid LineInput> lines){}
 @PostMapping("/enquiries/{id}/quotations") @Transactional ResponseEntity<?> createQuote(@PathVariable UUID id,@Valid @RequestBody QuoteInput r){Enquiry e=enquiry(id);Quotation q=new Quotation();q.setTenantId(tenant());q.setCreatedBy(user());q.setEnquiryId(e.getId());q.setCustomerId(e.getCustomerId());q.setQuotationNumber("QT-"+Year.now().getValue()+"-"+String.format("%06d",jdbc.queryForObject("select nextval('quotation_code_seq')",Long.class)));apply(q,r);quotes.save(q);saveLines(q,r.lines());e.setStatus("QUOTED");enquiries.save(e);return ResponseEntity.status(201).body(quoteDetail(q));}
 @GetMapping("/quotations") Object quotations(@RequestParam(defaultValue="") String search,@RequestParam(required=false) UUID customerId,@RequestParam(defaultValue="") String status,@RequestParam(required=false) LocalDate from,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return quotes.search(tenant(),search,customerId,status,from==null?null:from.atStartOfDay(ZoneOffset.UTC).toInstant(),PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::quoteSummary);}
 @GetMapping("/quotations/{id}") Object getQuote(@PathVariable UUID id){return quoteDetail(quote(id));}
 @PutMapping("/quotations/{id}") @Transactional Object updateQuote(@PathVariable UUID id,@Valid @RequestBody QuoteInput r){Quotation q=quote(id);if(!q.getStatus().equals("DRAFT"))throw new ApiException(409,"QUOTE_LOCKED","Only draft quotations can be edited");apply(q,r);quotes.save(q);lines.deleteByTenantIdAndQuotationId(tenant(),id);lines.flush();saveLines(q,r.lines());return quoteDetail(q);}
 void apply(Quotation q,QuoteInput r){if(r.lines()==null||r.lines().isEmpty())throw new ApiException(400,"VALIDATION_ERROR","Add at least one charge");if(!r.currency().matches("[A-Za-z]{3}"))throw new ApiException(400,"VALIDATION_ERROR","Currency must be a three-letter code");q.setCurrency(r.currency().toUpperCase());q.setTransitTimeText(r.transitTimeText());q.setValidUntil(r.validUntil());q.setTermsAndConditions(r.termsAndConditions());q.setNotes(r.notes());q.setTotalAmount(r.lines().stream().map(l->l.quantity().multiply(l.unitPrice())).reduce(BigDecimal.ZERO,BigDecimal::add));}
 void saveLines(Quotation q,List<LineInput> ls){int i=0;for(LineInput r:ls){QuotationLine l=new QuotationLine();l.setTenantId(tenant());l.setQuotationId(q.getId());l.setDescription(r.description());l.setQuantity(r.quantity());l.setUnitPrice(r.unitPrice());l.setAmount(r.quantity().multiply(r.unitPrice()));l.setSortOrder(i++);lines.save(l);}}
 Map<String,Object> quoteSummary(Quotation q){Map<String,Object> m=new LinkedHashMap<>();m.put("id",q.getId());m.put("quotationNumber",q.getQuotationNumber());m.put("customerName",customer(q.getCustomerId()).getCompanyName());m.put("customerId",q.getCustomerId());m.put("enquiryId",q.getEnquiryId());m.put("currency",q.getCurrency());m.put("totalAmount",q.getTotalAmount());m.put("status",q.getStatus());m.put("validUntil",q.getValidUntil());m.put("createdAt",q.getCreatedAt());return m;}
 Object quoteDetail(Quotation q){Map<String,Object> m=new LinkedHashMap<>(quoteSummary(q));m.put("quotation",q);m.put("lines",lines.findByTenantIdAndQuotationIdOrderBySortOrder(tenant(),q.getId()));m.put("enquiry",enquiryDetail(enquiry(q.getEnquiryId())));m.put("customer",customerSummary(customer(q.getCustomerId())));return m;}
 @GetMapping("/dashboard/summary") Object dashboard(){Map<String,Object> m=new LinkedHashMap<>();m.put("newEnquiries",enquiries.countByTenantIdAndStatus(tenant(),"NEW"));m.put("quotesPending",quotes.countByTenantIdAndStatus(tenant(),"DRAFT"));m.put("quotesSent",quotes.countByTenantIdAndStatus(tenant(),"SENT"));m.put("customers",customers.countByTenantId(tenant()));m.put("recentEnquiries",enquiries.findTop5ByTenantIdOrderByCreatedAtDesc(tenant()).stream().map(this::enquirySummary).toList());m.put("expiringQuotes",quotes.findTop5ByTenantIdAndStatusAndValidUntilLessThanEqual(tenant(),"DRAFT",LocalDate.now().plusDays(1)).stream().map(this::quoteSummary).toList());return m;}
 @GetMapping("/search") Object search(@RequestParam String q){if(q.trim().length()<2)return Map.of("customers",List.of(),"enquiries",List.of(),"quotations",List.of());return Map.of("customers",customers.searchTop(tenant(),q,PageRequest.of(0,5)).stream().map(this::customerSummary).toList(),"enquiries",enquiries.findTop5ByTenantIdAndEnquiryCodeContainingIgnoreCase(tenant(),q).stream().map(this::enquirySummary).toList(),"quotations",quotes.findTop5ByTenantIdAndQuotationNumberContainingIgnoreCase(tenant(),q).stream().map(this::quoteSummary).toList());}
}
