import {apiFetch} from './api';
import {useEffect,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {ArrowRight,Copy,Search,Sparkles,X} from 'lucide-react';
import './ai.css';

type Action={label:string,path:string,body?:unknown};
async function aiPost(path:string,body:unknown={}){const response=await apiFetch('/ai'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||'AI is temporarily unavailable. You can continue manually.');return data}
export function AiActionCard({title,description,actions}:{title:string,description?:string,actions:Action[]}){
 const [working,setWorking]=useState('');const [error,setError]=useState('');const [output,setOutput]=useState<any>(null);
 const run=async(action:Action)=>{setWorking(action.label);setError('');setOutput(null);try{setOutput(await aiPost(action.path,action.body))}catch(e:any){setError(e.message)}finally{setWorking('')}};
 return <section className="ai-action-card"><div className="ai-action-heading"><span><Sparkles size={15}/> FreightFlow AI <b>Beta</b></span><h3>{title}</h3>{description&&<p>{description}</p>}</div><div className="ai-action-buttons">{actions.map(action=><button className="btn secondary" key={action.label} disabled={!!working} onClick={()=>run(action)}>{working===action.label?'Working…':action.label}</button>)}</div>{working&&<div className="ai-progress" role="status"><div className="skeleton"/>Preparing a suggestion…</div>}{error&&<p className="ai-error" role="alert">{error}</p>}{output&&<div className="ai-action-result"><strong>{output.suggestions?'AI suggestions — review before using':output.label||'AI-generated draft — review before using'}</strong>{output.missingFields?.length>0&&<p>Missing: {output.missingFields.join(', ')}</p>}{output.suggestions?(output.suggestions.length?<ul>{output.suggestions.map((item:string,index:number)=><li key={index}>{item}</li>)}</ul>:<p>No inconsistencies found in the saved quotation.</p>):<textarea aria-label="Editable AI draft" defaultValue={output.draft||output.summary||''} rows={6} id="ai-action-draft"/>}{!output.suggestions&&<button className="ai-copy" onClick={()=>navigator.clipboard.writeText((document.getElementById('ai-action-draft') as HTMLTextAreaElement)?.value||'')}><Copy size={14}/> Copy reviewed draft</button>}</div>}</section>
}
export function GlobalAiDrawer({onClose}:{onClose:()=>void}){
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[onClose]);
 const {pathname}=useLocation();const [question,setQuestion]=useState('');const [working,setWorking]=useState(false);const [error,setError]=useState('');const [results,setResults]=useState<any>(null);
 const enquiryId=pathname.match(/^\/enquiries\/([^/]+)$/)?.[1];const quoteId=pathname.match(/^\/quotations\/([^/]+)(?:\/edit)?$/)?.[1];const customerId=pathname.match(/^\/customers\/([^/]+)$/)?.[1];
 const search=async()=>{setWorking(true);setError('');try{setResults(await aiPost('/search',{text:question}))}catch(e:any){setError(e.message)}finally{setWorking(false)}};
 const entityPath=results?.entity==='ENQUIRY'?'enquiries':results?.entity==='QUOTATION'?'quotations':'customers';
 return <div className="ai-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><aside className="ai-drawer" role="dialog" aria-modal="true" aria-label="FreightFlow AI"><header className="ai-drawer-head"><div><span className="ai-brand"><Sparkles size={16}/> FreightFlow AI <b>Beta</b></span><h2>Ask AI</h2><p>Choose a focused action for the page you're working on.</p></div><button aria-label="Close AI" onClick={onClose}><X size={19}/></button></header><div className="ai-drawer-body"><div className="ai-global-actions"><Link to="/enquiries/new?ai=intake" onClick={onClose}><Sparkles size={16}/> Extract shipment details <ArrowRight size={15}/></Link>{enquiryId&&<Link to={pathname} onClick={onClose}><Sparkles size={16}/> Find missing information or draft a message <ArrowRight size={15}/></Link>}{quoteId&&<Link to={'/quotations/'+quoteId+'/edit'} onClick={onClose}><Sparkles size={16}/> Prepare wording or check this quote <ArrowRight size={15}/></Link>}{customerId&&<Link to={pathname} onClick={onClose}><Sparkles size={16}/> Summarize this customer <ArrowRight size={15}/></Link>}</div><div className="ai-search-panel"><h3>Natural-language search</h3><p>Search existing FreightFlow records with safe filters.</p><label htmlFor="ai-search-question">Search request</label><input id="ai-search-question" autoFocus maxLength={500} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. Show ocean enquiries from Thailand"/><button className="btn primary" disabled={!question.trim()||working} onClick={search}><Search size={15}/>{working?'Searching…':'Search'}</button>{error&&<p className="ai-error" role="alert">{error}</p>}{results&&<div className="ai-search-results"><strong>{results.results?.length||0} results</strong>{results.results?.map((item:any)=><Link key={item.id} to={`/${entityPath}/${item.id}`} onClick={onClose}>{item.label}<small>{item.detail}</small></Link>)}</div>}</div></div><footer className="ai-drawer-footer"><button className="btn secondary" onClick={onClose}>Close</button></footer></aside></div>
}
